CI: Change coverage report to vladopajic/go-test-coverage

diff --git a/.github/workflows/go-pr.yaml b/.github/workflows/go-pr.yaml
--- a/.github/workflows/go-pr.yaml
+++ b/.github/workflows/go-pr.yaml
@@ -22,13 +22,53 @@ jobs:
       run: go build -v ./...
 
     - name: Test
-      run: go test -v -cover -coverprofile=coverage.txt ./...
+      run: go test -v ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
 
-    - name: Archive code coverage results
-      uses: actions/upload-artifact@v4
+    - name: Coverage
+      uses: vladopajic/go-test-coverage@v2
       with:
-        name: code-coverage
-        path: coverage.txt
+        config: ./.testcoverage.yml
+
+    # Written based on https://github.com/vladopajic/go-test-coverage/blob/main/docs/github_action.md
+    - name: Find pull request ID
+      run: |
+          PR_DATA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+          "https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:${{ github.ref_name }}&state=open")
+          PR_ID=$(echo "$PR_DATA" | jq -r '.[0].number')
+          
+          if [ "$PR_ID" != "null" ]; then
+          echo "pull_request_id=$PR_ID" >> $GITHUB_ENV
+          else
+          echo "No open pull request found for this branch."
+          fi
+    
+    - name: Is report present
+      if: env.pull_request_id
+      uses: peter-evans/find-comment@v3
+      id: fc
+      with:
+        issue-number: ${{ env.pull_request_id }}
+        comment-author: 'github-actions[bot]'
+        body-includes: 'go-test-coverage report:'
+    
+    - name: Post coverage report
+      if: env.pull_request_id
+      uses: peter-evans/create-or-update-comment@v4
+      with:
+        token: ${{ secrets.GITHUB_TOKEN }}
+        issue-number: ${{ env.pull_request_id }}
+        comment-id: ${{ steps.fc.outputs.comment-id }}
+        body: |
+          go-test-coverage report:
+          ```
+          ${{ fromJSON(steps.coverage.outputs.report) }} 
+          ```
+        edit-mode: replace
+
+    - name: Check coverage
+      if: steps.coverage.outcome == 'failure'
+      shell: bash
+      run: echo "coverage check failed" && exit 1
   
   # Skip linting part as for now
   #Lint:
@@ -44,18 +84,3 @@ jobs:
   #      uses: golangci/golangci-lint-action@v6
   #      with:
   #        version: v1.62
-
-  Coverage:
-    name: "Code coverage report"
-    if: github.event_name == 'pull_request' # Do not run when workflow is triggered by push to main branch
-    runs-on: ubuntu-latest
-    needs: Build # Depends on the artifact uploaded by the "Build" job
-    permissions:
-      contents:      read
-      actions:       read  # to download code coverage results from "Build" job
-      pull-requests: write # write permission needed to comment on PR
-    steps:
-      - uses: fgrosse/go-coverage-report@v1.2.0
-        with:
-          coverage-artifact-name: "code-coverage"
-          coverage-file-name: "coverage.txt"
